version: '3.5'

services:
  freegpt-webui:
    image: freegpt-webui
    container_name: freegpt-webui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./proxychains.conf:/etc/proxychains.conf
    ports:
      - "1338:1338"
